transformer_model: vit_base_patch16_224
model_provider: timm
pretrained: False
num_classes: 10
dataset: cifar10
loss_function: class_balanced_loss
optimizer: Adam
learning_rate: 0.00001
weight_decay: 0.00001
class_names: ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
data_root: '/datasets/cifar'
imb_type: 'exp'
imb_factor: 0.1
random_seed: 0
test_ratio: 0.8
batch_size: 12
num_workers: 15
num_epochs: 80
img_size: 224
per_class_metrics: True
kshot_metrics: True
few_medium_many_partition_strategy: '30-40-30'
focal_loss_gamma: 2.0
class_weights: [] # to be computed dynamically at start of training
class_balanced_loss_type: 'focal_loss'
class_balanced_beta: 0.9999
class_weights_strategy: frequency
mixup: True
mixup_alpha: 1.0
mixup_stop_epoch: 60
randaug_num_ops: 2
randaug_magnitude: 10
