program: hyper_opt.py
project: attention_long_tail
method: grid
metric:
  name : val/accuracy
  goal : maximize

parameters:
  learning_rate:
    values: [0.00005, 0.000001]
  weight_decay:
    values: [0.0001]
  imb_factor:
    values: [0.1, 0.01]
  optimizer:
    values: ['Adam']