transformer_model: vit_base_patch16_224
model_provider: timm
pretrained: False
num_classes: 1000
dataset: imagenet
loss_function: cross_entropy
optimizer: Adam
sgd_momentum: 0
learning_rate: 0.00001
weight_decay: 0.00001
class_names: 'data/imagenet_class_names.json'
random_seed: 0
batch_size: 112
num_workers: 15
num_epochs: 15
img_size: 224
per_class_metrics: False
kshot_metrics: True
focal_loss_gamma: 2.0
few_medium_many_partition_strategy: '30-40-30'
class_weights: []
class_balanced_loss_type: 'cross_entropy'
class_balanced_beta: 0.9999
class_weights_strategy: frequency
mixup: True
mixup_alpha: 1.0
mixup_stop_epoch: 10
randaug_num_ops: 2
randaug_magnitude: 10