transformer_model: vit_base_patch16_224
model_provider: timm
pretrained: False
num_classes: 100
dataset: cifar100
loss_function: cross_entropy
optimizer: Adam
sgd_momentum: 0
learning_rate: 0.00001
weight_decay: 0.00001
class_names: 'configs/cifar100_class_names.yaml'
data_root: '/media/nazirnayal/DATA/datasets/cifar100'
imb_type: 'exp'
imb_factor: 0.01
random_seed: 0
test_ratio: 0.8
batch_size: 12
num_workers: 15
num_epochs: 50
img_size: 224